USE [master]
GO



/****** Object:  Database [CECAM]    Script Date: 05/11/2022 23:04:33 ******/
CREATE DATABASE [CECAM]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CECAM', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\CECAM.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CECAM_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\CECAM_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CECAM].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CECAM] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CECAM] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CECAM] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CECAM] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CECAM] SET ARITHABORT OFF 
GO

ALTER DATABASE [CECAM] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CECAM] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CECAM] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CECAM] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CECAM] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CECAM] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CECAM] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CECAM] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CECAM] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CECAM] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CECAM] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CECAM] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CECAM] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CECAM] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CECAM] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CECAM] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CECAM] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CECAM] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [CECAM] SET  MULTI_USER 
GO

ALTER DATABASE [CECAM] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CECAM] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CECAM] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CECAM] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CECAM] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CECAM] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [CECAM] SET QUERY_STORE = OFF
GO

ALTER DATABASE [CECAM] SET  READ_WRITE 
GO


